services:
  - type: web
    name: baby-tracker
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server-db.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    domains:
      - baby-tracker.onrender.com 